In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [27]:
from sklearn.datasets import load_iris

In [28]:
i= load_iris()

In [29]:
dir(i)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [30]:
#using cross_val_score approach
from sklearn.model_selection import cross_val_score
print(cross_val_score(tree.DecisionTreeClassifier(),i.data,i.target,cv=3))
print(cross_val_score(RandomForestClassifier(),i.data,i.target,cv=3))


[0.98 0.92 0.98]
[0.98 0.94 0.92]


In [31]:
#scaling data for logistic regression
from sklearn.preprocessing import StandardScaler
s= StandardScaler().fit(i.data)
s
s.mean_
s.scale_
X=s.transform(i.data)


In [32]:
print(cross_val_score(LogisticRegression(),X,i.target,cv=3))

[0.98 0.96 0.96]
